// source: in_sdk_body.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!

goog.provide('proto.insider.sdk.Body');

goog.require('jspb.BinaryReader');
goog.require('jspb.BinaryWriter');
goog.require('jspb.Message');
goog.require('proto.insider.sdk.Content');
goog.require('proto.insider.sdk.UserSessionMsg');

goog.forwardDeclare('proto.insider.sdk.OperationType');
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.insider.sdk.Body = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.insider.sdk.Body, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.insider.sdk.Body.displayName = 'proto.insider.sdk.Body';
}



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.insider.sdk.Body.prototype.toObject = function(opt_includeInstance) {
  return proto.insider.sdk.Body.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.insider.sdk.Body} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.insider.sdk.Body.toObject = function(includeInstance, msg) {
  var f, obj = {
    userSession: (f = msg.getUserSession()) && proto.insider.sdk.UserSessionMsg.toObject(includeInstance, f),
    url: jspb.Message.getFieldWithDefault(msg, 2, ""),
    method: jspb.Message.getFieldWithDefault(msg, 3, 0),
    content: (f = msg.getContent()) && proto.insider.sdk.Content.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.insider.sdk.Body}
 */
proto.insider.sdk.Body.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.insider.sdk.Body;
  return proto.insider.sdk.Body.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.insider.sdk.Body} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.insider.sdk.Body}
 */
proto.insider.sdk.Body.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new proto.insider.sdk.UserSessionMsg;
      reader.readMessage(value,proto.insider.sdk.UserSessionMsg.deserializeBinaryFromReader);
      msg.setUserSession(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setUrl(value);
      break;
    case 3:
      var value = /** @type {!proto.insider.sdk.OperationType} */ (reader.readEnum());
      msg.setMethod(value);
      break;
    case 5:
      var value = new proto.insider.sdk.Content;
      reader.readMessage(value,proto.insider.sdk.Content.deserializeBinaryFromReader);
      msg.setContent(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.insider.sdk.Body.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.insider.sdk.Body.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.insider.sdk.Body} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.insider.sdk.Body.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getUserSession();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      proto.insider.sdk.UserSessionMsg.serializeBinaryToWriter
    );
  }
  f = message.getUrl();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
  f = message.getMethod();
  if (f !== 0.0) {
    writer.writeEnum(
      3,
      f
    );
  }
  f = message.getContent();
  if (f != null) {
    writer.writeMessage(
      5,
      f,
      proto.insider.sdk.Content.serializeBinaryToWriter
    );
  }
};


/**
 * optional UserSessionMsg user_session = 1;
 * @return {?proto.insider.sdk.UserSessionMsg}
 */
proto.insider.sdk.Body.prototype.getUserSession = function() {
  return /** @type{?proto.insider.sdk.UserSessionMsg} */ (
    jspb.Message.getWrapperField(this, proto.insider.sdk.UserSessionMsg, 1));
};


/**
 * @param {?proto.insider.sdk.UserSessionMsg|undefined} value
 * @return {!proto.insider.sdk.Body} returns this
*/
proto.insider.sdk.Body.prototype.setUserSession = function(value) {
  return jspb.Message.setWrapperField(this, 1, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.insider.sdk.Body} returns this
 */
proto.insider.sdk.Body.prototype.clearUserSession = function() {
  return this.setUserSession(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.insider.sdk.Body.prototype.hasUserSession = function() {
  return jspb.Message.getField(this, 1) != null;
};


/**
 * optional string url = 2;
 * @return {string}
 */
proto.insider.sdk.Body.prototype.getUrl = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/**
 * @param {string} value
 * @return {!proto.insider.sdk.Body} returns this
 */
proto.insider.sdk.Body.prototype.setUrl = function(value) {
  return jspb.Message.setProto3StringField(this, 2, value);
};


/**
 * optional OperationType method = 3;
 * @return {!proto.insider.sdk.OperationType}
 */
proto.insider.sdk.Body.prototype.getMethod = function() {
  return /** @type {!proto.insider.sdk.OperationType} */ (jspb.Message.getFieldWithDefault(this, 3, 0));
};


/**
 * @param {!proto.insider.sdk.OperationType} value
 * @return {!proto.insider.sdk.Body} returns this
 */
proto.insider.sdk.Body.prototype.setMethod = function(value) {
  return jspb.Message.setProto3EnumField(this, 3, value);
};


/**
 * optional Content content = 5;
 * @return {?proto.insider.sdk.Content}
 */
proto.insider.sdk.Body.prototype.getContent = function() {
  return /** @type{?proto.insider.sdk.Content} */ (
    jspb.Message.getWrapperField(this, proto.insider.sdk.Content, 5));
};


/**
 * @param {?proto.insider.sdk.Content|undefined} value
 * @return {!proto.insider.sdk.Body} returns this
*/
proto.insider.sdk.Body.prototype.setContent = function(value) {
  return jspb.Message.setWrapperField(this, 5, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.insider.sdk.Body} returns this
 */
proto.insider.sdk.Body.prototype.clearContent = function() {
  return this.setContent(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.insider.sdk.Body.prototype.hasContent = function() {
  return jspb.Message.getField(this, 5) != null;
};


