// source: in_sdk_header.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!

goog.provide('proto.insider.sdk.Header');

goog.require('jspb.BinaryReader');
goog.require('jspb.BinaryWriter');
goog.require('jspb.Message');
goog.require('proto.insider.sdk.DataTime');
goog.require('proto.insider.sdk.Host');

goog.forwardDeclare('proto.insider.sdk.DataFlow');
goog.forwardDeclare('proto.insider.sdk.DataProto');
goog.forwardDeclare('proto.insider.sdk.SdkMagic');
goog.forwardDeclare('proto.insider.sdk.SdkVersion');
goog.forwardDeclare('proto.insider.sdk.TransProto');
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.insider.sdk.Header = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.insider.sdk.Header, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.insider.sdk.Header.displayName = 'proto.insider.sdk.Header';
}



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.insider.sdk.Header.prototype.toObject = function(opt_includeInstance) {
  return proto.insider.sdk.Header.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.insider.sdk.Header} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.insider.sdk.Header.toObject = function(includeInstance, msg) {
  var f, obj = {
    msgMagic: jspb.Message.getFieldWithDefault(msg, 1, 0),
    version: jspb.Message.getFieldWithDefault(msg, 2, 0),
    packId: jspb.Message.getFieldWithDefault(msg, 3, 0),
    time: (f = msg.getTime()) && proto.insider.sdk.DataTime.toObject(includeInstance, f),
    dataDir: jspb.Message.getFieldWithDefault(msg, 5, 0),
    host: (f = msg.getHost()) && proto.insider.sdk.Host.toObject(includeInstance, f),
    transProto: jspb.Message.getFieldWithDefault(msg, 7, 0),
    dataProto: jspb.Message.getFieldWithDefault(msg, 8, 0)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.insider.sdk.Header}
 */
proto.insider.sdk.Header.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.insider.sdk.Header;
  return proto.insider.sdk.Header.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.insider.sdk.Header} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.insider.sdk.Header}
 */
proto.insider.sdk.Header.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {!proto.insider.sdk.SdkMagic} */ (reader.readEnum());
      msg.setMsgMagic(value);
      break;
    case 2:
      var value = /** @type {!proto.insider.sdk.SdkVersion} */ (reader.readEnum());
      msg.setVersion(value);
      break;
    case 3:
      var value = /** @type {number} */ (reader.readInt64());
      msg.setPackId(value);
      break;
    case 4:
      var value = new proto.insider.sdk.DataTime;
      reader.readMessage(value,proto.insider.sdk.DataTime.deserializeBinaryFromReader);
      msg.setTime(value);
      break;
    case 5:
      var value = /** @type {!proto.insider.sdk.DataFlow} */ (reader.readEnum());
      msg.setDataDir(value);
      break;
    case 6:
      var value = new proto.insider.sdk.Host;
      reader.readMessage(value,proto.insider.sdk.Host.deserializeBinaryFromReader);
      msg.setHost(value);
      break;
    case 7:
      var value = /** @type {!proto.insider.sdk.TransProto} */ (reader.readEnum());
      msg.setTransProto(value);
      break;
    case 8:
      var value = /** @type {!proto.insider.sdk.DataProto} */ (reader.readEnum());
      msg.setDataProto(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.insider.sdk.Header.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.insider.sdk.Header.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.insider.sdk.Header} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.insider.sdk.Header.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getMsgMagic();
  if (f !== 0.0) {
    writer.writeEnum(
      1,
      f
    );
  }
  f = message.getVersion();
  if (f !== 0.0) {
    writer.writeEnum(
      2,
      f
    );
  }
  f = message.getPackId();
  if (f !== 0) {
    writer.writeInt64(
      3,
      f
    );
  }
  f = message.getTime();
  if (f != null) {
    writer.writeMessage(
      4,
      f,
      proto.insider.sdk.DataTime.serializeBinaryToWriter
    );
  }
  f = message.getDataDir();
  if (f !== 0.0) {
    writer.writeEnum(
      5,
      f
    );
  }
  f = message.getHost();
  if (f != null) {
    writer.writeMessage(
      6,
      f,
      proto.insider.sdk.Host.serializeBinaryToWriter
    );
  }
  f = message.getTransProto();
  if (f !== 0.0) {
    writer.writeEnum(
      7,
      f
    );
  }
  f = message.getDataProto();
  if (f !== 0.0) {
    writer.writeEnum(
      8,
      f
    );
  }
};


/**
 * optional SdkMagic msg_magic = 1;
 * @return {!proto.insider.sdk.SdkMagic}
 */
proto.insider.sdk.Header.prototype.getMsgMagic = function() {
  return /** @type {!proto.insider.sdk.SdkMagic} */ (jspb.Message.getFieldWithDefault(this, 1, 0));
};


/**
 * @param {!proto.insider.sdk.SdkMagic} value
 * @return {!proto.insider.sdk.Header} returns this
 */
proto.insider.sdk.Header.prototype.setMsgMagic = function(value) {
  return jspb.Message.setProto3EnumField(this, 1, value);
};


/**
 * optional SdkVersion version = 2;
 * @return {!proto.insider.sdk.SdkVersion}
 */
proto.insider.sdk.Header.prototype.getVersion = function() {
  return /** @type {!proto.insider.sdk.SdkVersion} */ (jspb.Message.getFieldWithDefault(this, 2, 0));
};


/**
 * @param {!proto.insider.sdk.SdkVersion} value
 * @return {!proto.insider.sdk.Header} returns this
 */
proto.insider.sdk.Header.prototype.setVersion = function(value) {
  return jspb.Message.setProto3EnumField(this, 2, value);
};


/**
 * optional int64 pack_id = 3;
 * @return {number}
 */
proto.insider.sdk.Header.prototype.getPackId = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 3, 0));
};


/**
 * @param {number} value
 * @return {!proto.insider.sdk.Header} returns this
 */
proto.insider.sdk.Header.prototype.setPackId = function(value) {
  return jspb.Message.setProto3IntField(this, 3, value);
};


/**
 * optional DataTime time = 4;
 * @return {?proto.insider.sdk.DataTime}
 */
proto.insider.sdk.Header.prototype.getTime = function() {
  return /** @type{?proto.insider.sdk.DataTime} */ (
    jspb.Message.getWrapperField(this, proto.insider.sdk.DataTime, 4));
};


/**
 * @param {?proto.insider.sdk.DataTime|undefined} value
 * @return {!proto.insider.sdk.Header} returns this
*/
proto.insider.sdk.Header.prototype.setTime = function(value) {
  return jspb.Message.setWrapperField(this, 4, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.insider.sdk.Header} returns this
 */
proto.insider.sdk.Header.prototype.clearTime = function() {
  return this.setTime(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.insider.sdk.Header.prototype.hasTime = function() {
  return jspb.Message.getField(this, 4) != null;
};


/**
 * optional DataFlow data_dir = 5;
 * @return {!proto.insider.sdk.DataFlow}
 */
proto.insider.sdk.Header.prototype.getDataDir = function() {
  return /** @type {!proto.insider.sdk.DataFlow} */ (jspb.Message.getFieldWithDefault(this, 5, 0));
};


/**
 * @param {!proto.insider.sdk.DataFlow} value
 * @return {!proto.insider.sdk.Header} returns this
 */
proto.insider.sdk.Header.prototype.setDataDir = function(value) {
  return jspb.Message.setProto3EnumField(this, 5, value);
};


/**
 * optional Host host = 6;
 * @return {?proto.insider.sdk.Host}
 */
proto.insider.sdk.Header.prototype.getHost = function() {
  return /** @type{?proto.insider.sdk.Host} */ (
    jspb.Message.getWrapperField(this, proto.insider.sdk.Host, 6));
};


/**
 * @param {?proto.insider.sdk.Host|undefined} value
 * @return {!proto.insider.sdk.Header} returns this
*/
proto.insider.sdk.Header.prototype.setHost = function(value) {
  return jspb.Message.setWrapperField(this, 6, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.insider.sdk.Header} returns this
 */
proto.insider.sdk.Header.prototype.clearHost = function() {
  return this.setHost(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.insider.sdk.Header.prototype.hasHost = function() {
  return jspb.Message.getField(this, 6) != null;
};


/**
 * optional TransProto trans_proto = 7;
 * @return {!proto.insider.sdk.TransProto}
 */
proto.insider.sdk.Header.prototype.getTransProto = function() {
  return /** @type {!proto.insider.sdk.TransProto} */ (jspb.Message.getFieldWithDefault(this, 7, 0));
};


/**
 * @param {!proto.insider.sdk.TransProto} value
 * @return {!proto.insider.sdk.Header} returns this
 */
proto.insider.sdk.Header.prototype.setTransProto = function(value) {
  return jspb.Message.setProto3EnumField(this, 7, value);
};


/**
 * optional DataProto data_proto = 8;
 * @return {!proto.insider.sdk.DataProto}
 */
proto.insider.sdk.Header.prototype.getDataProto = function() {
  return /** @type {!proto.insider.sdk.DataProto} */ (jspb.Message.getFieldWithDefault(this, 8, 0));
};


/**
 * @param {!proto.insider.sdk.DataProto} value
 * @return {!proto.insider.sdk.Header} returns this
 */
proto.insider.sdk.Header.prototype.setDataProto = function(value) {
  return jspb.Message.setProto3EnumField(this, 8, value);
};


