// source: in_sdk.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!

goog.provide('proto.insider.sdk.Sdk');

goog.require('jspb.BinaryReader');
goog.require('jspb.BinaryWriter');
goog.require('jspb.Message');
goog.require('proto.insider.sdk.Body');
goog.require('proto.insider.sdk.Footer');
goog.require('proto.insider.sdk.Header');

/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.insider.sdk.Sdk = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.insider.sdk.Sdk, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.insider.sdk.Sdk.displayName = 'proto.insider.sdk.Sdk';
}



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.insider.sdk.Sdk.prototype.toObject = function(opt_includeInstance) {
  return proto.insider.sdk.Sdk.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.insider.sdk.Sdk} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.insider.sdk.Sdk.toObject = function(includeInstance, msg) {
  var f, obj = {
    header: (f = msg.getHeader()) && proto.insider.sdk.Header.toObject(includeInstance, f),
    body: (f = msg.getBody()) && proto.insider.sdk.Body.toObject(includeInstance, f),
    footer: (f = msg.getFooter()) && proto.insider.sdk.Footer.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.insider.sdk.Sdk}
 */
proto.insider.sdk.Sdk.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.insider.sdk.Sdk;
  return proto.insider.sdk.Sdk.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.insider.sdk.Sdk} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.insider.sdk.Sdk}
 */
proto.insider.sdk.Sdk.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new proto.insider.sdk.Header;
      reader.readMessage(value,proto.insider.sdk.Header.deserializeBinaryFromReader);
      msg.setHeader(value);
      break;
    case 2:
      var value = new proto.insider.sdk.Body;
      reader.readMessage(value,proto.insider.sdk.Body.deserializeBinaryFromReader);
      msg.setBody(value);
      break;
    case 3:
      var value = new proto.insider.sdk.Footer;
      reader.readMessage(value,proto.insider.sdk.Footer.deserializeBinaryFromReader);
      msg.setFooter(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.insider.sdk.Sdk.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.insider.sdk.Sdk.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.insider.sdk.Sdk} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.insider.sdk.Sdk.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getHeader();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      proto.insider.sdk.Header.serializeBinaryToWriter
    );
  }
  f = message.getBody();
  if (f != null) {
    writer.writeMessage(
      2,
      f,
      proto.insider.sdk.Body.serializeBinaryToWriter
    );
  }
  f = message.getFooter();
  if (f != null) {
    writer.writeMessage(
      3,
      f,
      proto.insider.sdk.Footer.serializeBinaryToWriter
    );
  }
};


/**
 * optional Header header = 1;
 * @return {?proto.insider.sdk.Header}
 */
proto.insider.sdk.Sdk.prototype.getHeader = function() {
  return /** @type{?proto.insider.sdk.Header} */ (
    jspb.Message.getWrapperField(this, proto.insider.sdk.Header, 1));
};


/**
 * @param {?proto.insider.sdk.Header|undefined} value
 * @return {!proto.insider.sdk.Sdk} returns this
*/
proto.insider.sdk.Sdk.prototype.setHeader = function(value) {
  return jspb.Message.setWrapperField(this, 1, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.insider.sdk.Sdk} returns this
 */
proto.insider.sdk.Sdk.prototype.clearHeader = function() {
  return this.setHeader(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.insider.sdk.Sdk.prototype.hasHeader = function() {
  return jspb.Message.getField(this, 1) != null;
};


/**
 * optional Body body = 2;
 * @return {?proto.insider.sdk.Body}
 */
proto.insider.sdk.Sdk.prototype.getBody = function() {
  return /** @type{?proto.insider.sdk.Body} */ (
    jspb.Message.getWrapperField(this, proto.insider.sdk.Body, 2));
};


/**
 * @param {?proto.insider.sdk.Body|undefined} value
 * @return {!proto.insider.sdk.Sdk} returns this
*/
proto.insider.sdk.Sdk.prototype.setBody = function(value) {
  return jspb.Message.setWrapperField(this, 2, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.insider.sdk.Sdk} returns this
 */
proto.insider.sdk.Sdk.prototype.clearBody = function() {
  return this.setBody(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.insider.sdk.Sdk.prototype.hasBody = function() {
  return jspb.Message.getField(this, 2) != null;
};


/**
 * optional Footer footer = 3;
 * @return {?proto.insider.sdk.Footer}
 */
proto.insider.sdk.Sdk.prototype.getFooter = function() {
  return /** @type{?proto.insider.sdk.Footer} */ (
    jspb.Message.getWrapperField(this, proto.insider.sdk.Footer, 3));
};


/**
 * @param {?proto.insider.sdk.Footer|undefined} value
 * @return {!proto.insider.sdk.Sdk} returns this
*/
proto.insider.sdk.Sdk.prototype.setFooter = function(value) {
  return jspb.Message.setWrapperField(this, 3, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.insider.sdk.Sdk} returns this
 */
proto.insider.sdk.Sdk.prototype.clearFooter = function() {
  return this.setFooter(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.insider.sdk.Sdk.prototype.hasFooter = function() {
  return jspb.Message.getField(this, 3) != null;
};


