// source: in_sdk_body_user.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!

goog.provide('proto.insider.sdk.UserSession');
goog.provide('proto.insider.sdk.UserSession.Result');
goog.provide('proto.insider.sdk.UserSession.UserMethod');

goog.require('jspb.BinaryReader');
goog.require('jspb.BinaryWriter');
goog.require('jspb.Message');
goog.require('proto.insider.sdk.UserBaseInfo');

/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.insider.sdk.UserSession = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.insider.sdk.UserSession, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.insider.sdk.UserSession.displayName = 'proto.insider.sdk.UserSession';
}



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.insider.sdk.UserSession.prototype.toObject = function(opt_includeInstance) {
  return proto.insider.sdk.UserSession.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.insider.sdk.UserSession} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.insider.sdk.UserSession.toObject = function(includeInstance, msg) {
  var f, obj = {
    userType: jspb.Message.getFieldWithDefault(msg, 1, 0),
    user: (f = msg.getUser()) && proto.insider.sdk.UserBaseInfo.toObject(includeInstance, f),
    token: jspb.Message.getFieldWithDefault(msg, 3, ""),
    aliveTime: jspb.Message.getFieldWithDefault(msg, 4, 0),
    result: jspb.Message.getFieldWithDefault(msg, 5, 0)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.insider.sdk.UserSession}
 */
proto.insider.sdk.UserSession.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.insider.sdk.UserSession;
  return proto.insider.sdk.UserSession.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.insider.sdk.UserSession} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.insider.sdk.UserSession}
 */
proto.insider.sdk.UserSession.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {!proto.insider.sdk.UserSession.UserMethod} */ (reader.readEnum());
      msg.setUserType(value);
      break;
    case 2:
      var value = new proto.insider.sdk.UserBaseInfo;
      reader.readMessage(value,proto.insider.sdk.UserBaseInfo.deserializeBinaryFromReader);
      msg.setUser(value);
      break;
    case 3:
      var value = /** @type {string} */ (reader.readString());
      msg.setToken(value);
      break;
    case 4:
      var value = /** @type {number} */ (reader.readUint64());
      msg.setAliveTime(value);
      break;
    case 5:
      var value = /** @type {!proto.insider.sdk.UserSession.Result} */ (reader.readEnum());
      msg.setResult(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.insider.sdk.UserSession.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.insider.sdk.UserSession.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.insider.sdk.UserSession} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.insider.sdk.UserSession.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getUserType();
  if (f !== 0.0) {
    writer.writeEnum(
      1,
      f
    );
  }
  f = message.getUser();
  if (f != null) {
    writer.writeMessage(
      2,
      f,
      proto.insider.sdk.UserBaseInfo.serializeBinaryToWriter
    );
  }
  f = message.getToken();
  if (f.length > 0) {
    writer.writeString(
      3,
      f
    );
  }
  f = message.getAliveTime();
  if (f !== 0) {
    writer.writeUint64(
      4,
      f
    );
  }
  f = message.getResult();
  if (f !== 0.0) {
    writer.writeEnum(
      5,
      f
    );
  }
};


/**
 * @enum {number}
 */
proto.insider.sdk.UserSession.UserMethod = {
  U_LOGIN: 0,
  U_LOGOUT: 1,
  U_VERI: 2,
  U_REGISTER: 3
};

/**
 * @enum {number}
 */
proto.insider.sdk.UserSession.Result = {
  U_OK: 0,
  U_ERROR: 1,
  U_TOKEN_TIMEOUT: 2,
  U_USER_EXIST: 3,
  U_USER_NOT_EXIST: 4,
  U_USER_BLACK: 5,
  US_USER_NO_PERMISSION: 6
};

/**
 * optional UserMethod user_type = 1;
 * @return {!proto.insider.sdk.UserSession.UserMethod}
 */
proto.insider.sdk.UserSession.prototype.getUserType = function() {
  return /** @type {!proto.insider.sdk.UserSession.UserMethod} */ (jspb.Message.getFieldWithDefault(this, 1, 0));
};


/**
 * @param {!proto.insider.sdk.UserSession.UserMethod} value
 * @return {!proto.insider.sdk.UserSession} returns this
 */
proto.insider.sdk.UserSession.prototype.setUserType = function(value) {
  return jspb.Message.setProto3EnumField(this, 1, value);
};


/**
 * optional UserBaseInfo user = 2;
 * @return {?proto.insider.sdk.UserBaseInfo}
 */
proto.insider.sdk.UserSession.prototype.getUser = function() {
  return /** @type{?proto.insider.sdk.UserBaseInfo} */ (
    jspb.Message.getWrapperField(this, proto.insider.sdk.UserBaseInfo, 2));
};


/**
 * @param {?proto.insider.sdk.UserBaseInfo|undefined} value
 * @return {!proto.insider.sdk.UserSession} returns this
*/
proto.insider.sdk.UserSession.prototype.setUser = function(value) {
  return jspb.Message.setWrapperField(this, 2, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.insider.sdk.UserSession} returns this
 */
proto.insider.sdk.UserSession.prototype.clearUser = function() {
  return this.setUser(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.insider.sdk.UserSession.prototype.hasUser = function() {
  return jspb.Message.getField(this, 2) != null;
};


/**
 * optional string token = 3;
 * @return {string}
 */
proto.insider.sdk.UserSession.prototype.getToken = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 3, ""));
};


/**
 * @param {string} value
 * @return {!proto.insider.sdk.UserSession} returns this
 */
proto.insider.sdk.UserSession.prototype.setToken = function(value) {
  return jspb.Message.setProto3StringField(this, 3, value);
};


/**
 * optional uint64 alive_time = 4;
 * @return {number}
 */
proto.insider.sdk.UserSession.prototype.getAliveTime = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 4, 0));
};


/**
 * @param {number} value
 * @return {!proto.insider.sdk.UserSession} returns this
 */
proto.insider.sdk.UserSession.prototype.setAliveTime = function(value) {
  return jspb.Message.setProto3IntField(this, 4, value);
};


/**
 * optional Result result = 5;
 * @return {!proto.insider.sdk.UserSession.Result}
 */
proto.insider.sdk.UserSession.prototype.getResult = function() {
  return /** @type {!proto.insider.sdk.UserSession.Result} */ (jspb.Message.getFieldWithDefault(this, 5, 0));
};


/**
 * @param {!proto.insider.sdk.UserSession.Result} value
 * @return {!proto.insider.sdk.UserSession} returns this
 */
proto.insider.sdk.UserSession.prototype.setResult = function(value) {
  return jspb.Message.setProto3EnumField(this, 5, value);
};


