// source: in_sdk_body_user.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!

goog.provide('proto.insider.sdk.UserAllInfo');

goog.require('jspb.BinaryReader');
goog.require('jspb.BinaryWriter');
goog.require('jspb.Message');
goog.require('proto.insider.sdk.UserBaseInfo');

/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.insider.sdk.UserAllInfo = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.insider.sdk.UserAllInfo, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.insider.sdk.UserAllInfo.displayName = 'proto.insider.sdk.UserAllInfo';
}



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.insider.sdk.UserAllInfo.prototype.toObject = function(opt_includeInstance) {
  return proto.insider.sdk.UserAllInfo.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.insider.sdk.UserAllInfo} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.insider.sdk.UserAllInfo.toObject = function(includeInstance, msg) {
  var f, obj = {
    userBaseInfo: (f = msg.getUserBaseInfo()) && proto.insider.sdk.UserBaseInfo.toObject(includeInstance, f),
    inBlacklist: jspb.Message.getBooleanFieldWithDefault(msg, 2, false),
    valid: jspb.Message.getBooleanFieldWithDefault(msg, 3, false)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.insider.sdk.UserAllInfo}
 */
proto.insider.sdk.UserAllInfo.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.insider.sdk.UserAllInfo;
  return proto.insider.sdk.UserAllInfo.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.insider.sdk.UserAllInfo} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.insider.sdk.UserAllInfo}
 */
proto.insider.sdk.UserAllInfo.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new proto.insider.sdk.UserBaseInfo;
      reader.readMessage(value,proto.insider.sdk.UserBaseInfo.deserializeBinaryFromReader);
      msg.setUserBaseInfo(value);
      break;
    case 2:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setInBlacklist(value);
      break;
    case 3:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setValid(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.insider.sdk.UserAllInfo.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.insider.sdk.UserAllInfo.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.insider.sdk.UserAllInfo} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.insider.sdk.UserAllInfo.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getUserBaseInfo();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      proto.insider.sdk.UserBaseInfo.serializeBinaryToWriter
    );
  }
  f = message.getInBlacklist();
  if (f) {
    writer.writeBool(
      2,
      f
    );
  }
  f = message.getValid();
  if (f) {
    writer.writeBool(
      3,
      f
    );
  }
};


/**
 * optional UserBaseInfo user_base_info = 1;
 * @return {?proto.insider.sdk.UserBaseInfo}
 */
proto.insider.sdk.UserAllInfo.prototype.getUserBaseInfo = function() {
  return /** @type{?proto.insider.sdk.UserBaseInfo} */ (
    jspb.Message.getWrapperField(this, proto.insider.sdk.UserBaseInfo, 1));
};


/**
 * @param {?proto.insider.sdk.UserBaseInfo|undefined} value
 * @return {!proto.insider.sdk.UserAllInfo} returns this
*/
proto.insider.sdk.UserAllInfo.prototype.setUserBaseInfo = function(value) {
  return jspb.Message.setWrapperField(this, 1, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.insider.sdk.UserAllInfo} returns this
 */
proto.insider.sdk.UserAllInfo.prototype.clearUserBaseInfo = function() {
  return this.setUserBaseInfo(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.insider.sdk.UserAllInfo.prototype.hasUserBaseInfo = function() {
  return jspb.Message.getField(this, 1) != null;
};


/**
 * optional bool in_blacklist = 2;
 * @return {boolean}
 */
proto.insider.sdk.UserAllInfo.prototype.getInBlacklist = function() {
  return /** @type {boolean} */ (jspb.Message.getBooleanFieldWithDefault(this, 2, false));
};


/**
 * @param {boolean} value
 * @return {!proto.insider.sdk.UserAllInfo} returns this
 */
proto.insider.sdk.UserAllInfo.prototype.setInBlacklist = function(value) {
  return jspb.Message.setProto3BooleanField(this, 2, value);
};


/**
 * optional bool valid = 3;
 * @return {boolean}
 */
proto.insider.sdk.UserAllInfo.prototype.getValid = function() {
  return /** @type {boolean} */ (jspb.Message.getBooleanFieldWithDefault(this, 3, false));
};


/**
 * @param {boolean} value
 * @return {!proto.insider.sdk.UserAllInfo} returns this
 */
proto.insider.sdk.UserAllInfo.prototype.setValid = function(value) {
  return jspb.Message.setProto3BooleanField(this, 3, value);
};


